# Generated by Django 4.2.7 on 2025-07-26 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('prazo_recebimento', models.IntegerField(default=0, help_text='Prazo em dias para recebimento (0 = à vista)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, help_text='Forma de pagamento utilizada (apenas para saídas/vendas)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.formapagamento'),
        ),
    ]
