# Generated by Django 4.2.7 on 2025-08-12 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_venda_itemvenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.formapagamento'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('finalizada', 'Finalizada'), ('paga', 'Paga'), ('parcial', 'Pago Parcial'), ('cancelada', 'Cancelada')], default='aberta', max_length=20),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacao', models.TextField(blank=True)),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formapagamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.venda')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='ContasReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('aberto', 'Em Aberto'), ('parcial', 'Pago Parcial'), ('quitado', 'Quitado'), ('vencido', 'Vencido')], default='aberto', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_receber', to='core.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.venda')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
