# Generated by Django 4.2.7 on 2025-08-12 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_venda_forma_pagamento_alter_venda_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacao', models.TextField(blank=True)),
                ('conta_receber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_conta', to='core.contasreceber')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formapagamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento de Conta',
                'verbose_name_plural': 'Pagamentos de Contas',
                'ordering': ['-data_pagamento'],
            },
        ),
    ]
